import { ethers } from 'ethers';

import { default as kittyCoreContractDefinition } from './abi/KittyCore.json'
//generated by oz
import { default as kittyTraderContractDefinition } from './abi/KittyTrader.json'
//custom abi, replace with the ERC20UpgradeSafe abi
import { default as mohanTokenContractDefinition } from './abi/MohanToken.json'

export default function buildContracts(provider, addresses) {

    return {
        kittyTrader: new ethers.Contract(addresses.kittyTrader, kittyTraderContractDefinition.abi, provider.getSigner()),
        kittyCore: new ethers.Contract(addresses.kittyCore, kittyCoreContractDefinition.abi, provider.getSigner()),
        mohanToken: new ethers.Contract(addresses.mohanToken, mohanTokenContractDefinition.abi, provider.getSigner())
    }
}